name: Tests
on:
  pull_request:
    branches: [ develop, master ]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '15'
    - name: test
      run: |
        ulimit -n 65535
        mvn test
        mvn clean
        
